(ns mokepon.container)

(comment
  (cljsjs/react)
  (reset! (app-state) (mokepon.rpg/new-game))
  (.log js/console (clj->js (get-in @(app-state) [:locations-seen])))
  (take-chipu!)
  (set-cash! 1000)
  (buy-item! :candy)
  (buy-item! :mokebox)
  (go-to-location! :home)
  (go-to-location! :phone)
  (go-to-location! :shop)
  (go-to-location! :mokedex)
  (go-to-location! :outside)
  (go-to-location! :pool)
  (go-to-location! :forest))
